name: starling

services:
  starling:
    build:
      context: ../../
      dockerfile: Dockerfile
    image: ghcr.io/graycodeai/starling:dev
    env_file:
      - path: ../../.env.example
        required: false
